default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: amort_development

test:
  <<: *default
  database: amort_test

production:
  <<: *default
  database: amort_production
  username: postgres
  password: postgres