default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: amort_postgresql
  username: postgres
  host: localhost
  password: postgres

test:
  <<: *default
  database: amort_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
